name: Build 750Gr3

on:
  release:
    types: [published]

  push:
    branches:
      - stable

  schedule:
    - cron: 0 0 * * 0

  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/openwrt/buildbot/buildworker-3.4.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "openwrt"

      - name: Fix permission
        run: |
          chown -R buildbot:buildbot openwrt

      - name: Update & Install feeds
        shell: su buildbot -c "sh -e {0}"
        working-directory: openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configuration Customization - 750Gr3
        shell: su buildbot -c "sh -e {0}"
        working-directory: openwrt
        env:
          CONFIG_FILE: "750gr3.config"
        run: |
          wget https://gist.githubusercontent.com/msdx321/5d72b424ea4d7aa4cd0bd3c7003e1fcf/raw/$CONFIG_FILE
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE .config
          make defconfig

      - name: Build firmware
        shell: su buildbot -c "sh -e {0}"
        working-directory: openwrt
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware-750gr3
          path: openwrt/bin/targets/ramips/mt7621/openwrt-ramips-mt7621-mikrotik_routerboard-750gr3-squashfs-sysupgrade.bin
