name: Build E8450

on:
  release:
    types: [published]

  schedule:
    - cron: 0 0 * * 0

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/openwrt/buildbot/buildworker-3.4.1

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          path: "openwrt"
          submodules: 'recursive'

      - name: Fix permission
        run: |
          chown -R buildbot:buildbot openwrt

      - name: Update & Install feeds
        shell: su buildbot -c "sh -e {0}"
        working-directory: openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configuration Customization - E8450
        shell: su buildbot -c "sh -e {0}"
        working-directory: openwrt
        env:
          CONFIG_FILE: "e8450.config"
        run: |
          wget https://gist.githubusercontent.com/msdx321/5d72b424ea4d7aa4cd0bd3c7003e1fcf/raw/$CONFIG_FILE
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE .config
          make defconfig

      - name: Build firmware
        shell: su buildbot -c "sh -e {0}"
        working-directory: openwrt
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: firmware-e8450
          path: openwrt/bin/targets/mediatek/mt7622/openwrt-mediatek-mt7622-linksys_e8450-ubi-squashfs-sysupgrade.itb
